const axios = require('axios');

const handler = async (m, { conn, text, prefix, command }) => {
  if (!text) return m.reply(`Use the format:\n${prefix + command} text\nExample:\n${prefix + command} Hello terri😂`);

  try {
    const url = `https://aqul-brat.hf.space/?text=${encodeURIComponent(text)}`;
    const { data } = await axios.get(url, { responseType: 'arraybuffer' });

    await conn.sendImageAsSticker(m.chat, data, m, {
      packname: "Brat Generated by",
      author: "Terri"
    });

  } catch (err) {
    console.error(err);
    m.reply('❌ Failed to create sticker.');
  }
};

handler.help = ['brat <text>'];
handler.tags = ['maker'];
handler.command = ['brat', 'stickerbrat', 'stickertext'];

module.exports = handler;