let handler = async (m, { reply, usedPrefix }) => {
	reply(`_${pickRandom(global.bucin)}_`)
}
handler.help = ['quotesbucin']
handler.tags = ['quotes']
handler.command = ['quotesbucin']
module.exports = handler;

function pickRandom(list) {
 return list[Math.floor(list.length * Math.random())]
}

global.bucin = [
    "I choose to be alone, not because I'm waiting for the perfect one, but because I need someone who never gives up.",
    "A single person was created along with a partner they haven't found yet.",
    "Single. Maybe that's God's way of saying 'Take a rest from the wrong love'.",
    "Single is a young person who prioritizes personal development for a more classy love later.",
    "I'm not looking for someone perfect, but I'm looking for someone who becomes perfect thanks to my strengths.",
    "Other people's partners are our delayed soulmates.",
    "Being single will surely pass. Everything has its time, when all loneliness becomes togetherness with a lawful partner. Be patient.",
    "Romeo was willing to die for Juliet, Jack died saving Rose. The point is, if you want to stay alive, be single.",
    "I look for people not from their advantages but from the sincerity of their hearts.",
    "Soulmates aren't like flip-flops that often get swapped. So keep fighting the good fight.",
    "If you were a guitar string, I wouldn't want to be the guitarist. Because I don't want to break you.",
    "If loving you is an illusion, then let me imagine forever.",
    "Honey... My only task is to love you, not to fight fate.",
    "When I'm with you, 1 hour feels like 1 second, but if I'm far from you, 1 day feels like 1 year.",
    "Banana tofu kolak from Sumedang, even if distance stretches, my love will never disappear.",
    "I want to be the only one, not one of many.",
    "I can't promise to be good. But I promise I will always be by your side.",
    "If I were a people's representative I would definitely fail, how can I think about the people when all that's on my mind is you.",
    "Look at my garden, full of flowers. Look into your eyes, my heart blooms.",
    "Promise to stay with me now, tomorrow, and forever.",
    "Longing doesn't just arise because of separated distance. But also because of unfulfilled desires.",
    "You will never be far from me, wherever I go you are always there, because you are always in my heart, only our bodies are far apart, not our hearts.",
    "I know in every glance, we are hindered by distance and time. But I believe that later we can be united.",
    "Missing you without ever meeting is like creating a song that is never sung.",
    "Sometimes distance always becomes a barrier between me and you, but still in my heart we are always close.",
    "If this heart cannot hold back all the longing, what can I do but pray for you.",
    "Maybe at this time I can only hold back this longing. Until the time comes when I can meet and release this longing with you.",
    "Through the longing that boils in the heart, sometimes I really need your loving embrace.",
    "In the cold of the night, I no longer remember; How often I think of you and miss you.",
    "Missing you is like rain that comes suddenly and lasts long. And even after the rain stops, my longing still feels.",
    "Since knowing you, I always want to keep learning, learning to be the best for you.",
    "Do you know the difference between a pencil and your face? Pencil writing can be erased, but your face can't be erased from my mind.",
    "It's not the National Exam tomorrow that I have to worry about, but the life test I go through after you leave me.",
    "One happy thing at school that keeps me motivated is being able to see your smile every day.",
    "Do you know the difference between going to school and going to your house? If going to school must bring books and pens, but if going to your house, I just need to bring heart and love.",
    "I'm not sad if tomorrow is Monday, I'm sad if I don't meet you.",
    "My love moment is perpendicular to your love moment. Making our love a perfect equilibrium point.",
    "I'm willing to join a race around the world, as long as you are the finish line.",
    "My homework is missing you. Stronger than Mathematics, broader than Physics, more real than Biology.",
    "My love for you is like metabolism, which won't stop until death.",
    "If the ghost was like you, I'd pick you up when you come, and take you home when you leave.",
    "I'll eat anything as long as it's with you, including eating liver (heartache).",
    "Love is like a death sentence. If not shot, then hanged.",
    "Loving you is like drugs: once tried becomes addictive, not tried makes curious, left causes withdrawal.",
    "I really like snacking because snacking is delicious. Especially snacking on you completely...",
    "This world only belongs to the two of us. Others are just renting.",
    "For me, every day is Tuesday. Tuesday in Heaven when close to you...",
    "How about we both become criminal partners? I steal your heart and you steal mine.",
    "You are like the coffee I sipped this morning. Bitter, but addictive.",
    "I'm often jealous of your lipstick. It can kiss you every day, from morning to night.",
    "Just hearing your name can make me smile like a fool.",
    "I know you have more than one female friend, and I'm not the only one who likes you.",
    "Since I stopped hoping for you, I've become unmotivated in everything..",
    "With you, falling in love is the most intentional heartbreak.",
    "It's very difficult to feel happiness in life without your presence by my side.",
    "Through the boiling longing in my heart, sometimes I really need your loving embrace.",
    "If only you knew, until now I still love you.",
    "Sometimes I envy a kite..even if its string breaks, it's still chased and not willing to be taken by others...",
    "I didn't know what love was, until I met you. But, at that moment I also knew what heartbreak felt like.",
    "Chasing is tiring, but waiting is even more exhausting\nWaiting for you to realize my existence...",
    "Don't stop loving just because you've been hurt. Because there's no rainbow without rain, no true love without tears.",
    "I have a million reasons to forget you, but nothing can force me to stop loving you.",
    "Sometimes someone feels very stupid just to love someone.",
    "You are the best heartbreak I never regret.",
    "It's not that I'm not worth waiting for, it's just that I often give false hope.",
    "Part of me feels pain, Remembering him who is so close, but untouchable.",
    "The best thing about loving someone is silently praying for them.",
    "I hope I can eliminate these feelings as fast as I lost you.",
    "For love we deceive ourselves. Trying to be strong but actually falling dishonorably.",
    "Think of me as your home, if you leave you know where to return. Stay if you want and leave if you're bored...",
    "I'm confused, should I be disappointed or not? If I'm disappointed, who am I to him?\n\nIf I'm not disappointed, but I'm waiting for his words.",
    "My longing is like a branch that remains standing. Even though not a single leaf accompanies it, until it dries, breaks, and dies.",
    "I think we are now just two strangers who have the same memories.",
    "Make me able to hate you even if only for a few minutes, so it's not too heavy to forget you.",
    "I love you with all my heart, but you instead share your feelings with others.",
    "Loving you might destroy me, but somehow leaving you doesn't fix me.",
    "You are the first and foremost in my life. But, I am the second to you.",
    "If we can only meet in dreams, I want to sleep forever.",
    "Seeing you happy is my happiness, even if your happiness is without me.",
    "I sometimes envy an object. It has no feelings but is always needed. Unlike me who has feelings, but is abandoned and ignored...",
    "How can I move on if only with you my heart stops?",
    "Memories of you are already like home to me. So whenever my mind wanders, it will always end up returning to you.",
    "Why is tissue useful? Because love never dries up. - Sujiwo Tejo",
    "If loving you is a mistake, then so be it, let me keep being wrong.",
    "Since knowing you, I always want to keep learning. Learning to be the best for you.",
    "Someone acts foolish just to see you smile. And he feels happy about it.",
    "I'm not a good person, but I will learn to be the best for you.",
    "We don't die, but the wounds make us unable to walk like before anymore.",
    "Your existence is like a cup of coffee that I need every morning, which can push me to stay enthusiastic about living the day.",
    "I really want to give the world to you. But since that's not possible, then I will give you the most important thing in my life, which is my world.",
    "Better to be humorous but sweet, rather than pretending to be romantic but ending tragically.",
    "In the end not disappointed, we must understand when it's time to hope and when to stop.",
    "I am a Javanese who doesn't understand the meaning of 'I Love U'. But I understand it as 'I love you'.",
    "No need to be beautiful and rich, I'm happy enough if you're loyal.",
    "My love for you is like a camera, focused only on you, others are blurry.",
    "Every day carried in dreams but cannot possess.",
    "Not meeting you for 30 days feels like a month.",
    "Me without you is like cat rice losing its gravy. Scattered.",
    "I wish I could turn back time. So I could meet you earlier. So I have more time to live with you.",
    "I never knew what love was, except since meeting you.",
    "My love for you won't disappear even if I get married again.",
    "My patience has limits, but my love for you has no end.",
    "My love won't fade even if using Bayclean.",
    "Beautiful memories of being with you are remembered until forgotten.",
    "I won't be able to live alone, I need help from another person.",
    "My love for you is like a debt collector bank (endless).",
    "Our patience has limits, but our love for you will never end.",
    "I want to compile all the words of love that exist in this world, then gather them, so you know how big my love for you is.",
    "Don't worry, my love is like a Krispatih song; Never fading with time.",
    "I am not a perfect person for you, and not the best for you either. But certainly, I am the only person who always remembers you.",
    "Just let the network disappear, but don't you disappear.",
    "Often made to eat liver (heartbroken). But realizing you're still here makes me happy again.",
    "My enemies are those who want to have you too.",
    "Many are always there, but what if only you are the one I want?",
    "My sleep schedule is destroyed by longing.",
    "Just let China be far away, don't let our love be.",
    "What matters is your happiness, I'm not important..",
    "I only have one wish, to be loved by you..",
    "Me without you is like an ambulance without wee-oo wee-oo wee-oo.",
    "Just let Antarctica be far away. Don't let between us be far."
]